use std::sync::OnceLock;

// TODO: split activity_names into scalar and sequence.
// TODO: add sample attribute names.
// CONSIDER:

pub fn activity_names_all() -> &'static [&'static str] {
    static ALL: OnceLock<Vec<&'static str>> = OnceLock::new();
    ALL.get_or_init(|| [ACTIVITY_NAMES_PERSONAL, ACTIVITY_NAMES_MISC].concat())
}

pub const ACTIVITY_NAMES_PERSONAL: &[&str] = &[
    "Run",
    "Sport Climb",
    "Boulder",
    "Work",
    "Study",
    "Cycle",
    "Nelson Recruitment",
    "Push-Ups",
    "Deadlift",
];

pub const ATTRIBUTE_NAMES_PERSONAL: &[&str] = &["Reps", "RPE", "Class"];

pub const ACTIVITY_NAMES_MISC: &[&str] = &[
    // Strength — Squat
    "Back Squat",
    "Front Squat",
    "Overhead Squat",
    "Box Squat",
    "Pause Squat",
    "Safety Bar Squat",
    "Zercher Squat",
    "Goblet Squat",
    "Bulgarian Split Squat",
    "Pistol Squat",
    "Lateral Squat",
    // Strength — Hip Hinge
    "Deadlift",
    "Romanian Deadlift",
    "Sumo Deadlift",
    "Stiff-Leg Deadlift",
    "Trap Bar Deadlift",
    "Deficit Deadlift",
    "Rack Pull",
    "Paused Deadlift",
    "Snatch-Grip Deadlift",
    "Single-Leg Deadlift",
    "Good Morning",
    "Jefferson Curl",
    "Hip Hinge",
    // Strength — Press
    "Bench Press",
    "Incline Bench Press",
    "Decline Bench Press",
    "Close-Grip Bench Press",
    "Paused Bench Press",
    "Floor Press",
    "Spoto Press",
    "Pin Press",
    "Board Press",
    "Dumbbell Bench Press",
    "Incline Dumbbell Press",
    "Overhead Press",
    "Push Press",
    "Seated Dumbbell Press",
    "Arnold Press",
    "Landmine Press",
    "Single-Arm Overhead Press",
    "Pike Push-Up",
    "Handstand Push-Up",
    "Dips",
    "Chest Dip",
    "Ring Dip",
    "Push-Up",
    "Ring Push-Up",
    "Archer Push-Up",
    "One-Arm Push-Up",
    // Strength — Pull
    "Pull-Up",
    "Chin-Up",
    "Weighted Pull-Up",
    "Typewriter Pull-Up",
    "Commando Pull-Up",
    "Lat Pulldown",
    "Straight-Arm Pulldown",
    "Barbell Row",
    "Pendlay Row",
    "T-Bar Row",
    "Cable Row",
    "Dumbbell Row",
    "Chest-Supported Row",
    "Seal Row",
    "Meadows Row",
    "Kroc Row",
    "Inverted Row",
    "Landmine Row",
    "Face Pull",
    "Cable Pullover",
    "Dumbbell Pullover",
    // Strength — Curl / Tricep
    "Barbell Curl",
    "Dumbbell Curl",
    "Hammer Curl",
    "Preacher Curl",
    "Incline Dumbbell Curl",
    "Concentration Curl",
    "Reverse Curl",
    "Zottman Curl",
    "EZ Bar Curl",
    "Spider Curl",
    "Tricep Pushdown",
    "Skull Crusher",
    "Overhead Tricep Extension",
    "Tricep Kickback",
    "JM Press",
    // Strength — Leg
    "Leg Press",
    "Hack Squat",
    "Leg Extension",
    "Leg Curl",
    "Nordic Hamstring Curl",
    "Hip Thrust",
    "Glute Bridge",
    "Single-Leg Hip Thrust",
    "Lunge",
    "Reverse Lunge",
    "Walking Lunge",
    "Step-Up",
    "Calf Raise",
    "Seated Calf Raise",
    "Single-Leg Calf Raise",
    "Adductor Machine",
    "Abductor Machine",
    "Copenhagen Plank",
    // Strength — Shoulder / Upper Back
    "Lateral Raise",
    "Front Raise",
    "Rear Delt Fly",
    "Cable Fly",
    "Chest Fly",
    "Pec Deck",
    "Upright Row",
    "Shrug",
    "Banded Pull-Apart",
    "Wall Slide",
    "External Rotation",
    "Rotator Cuff Strengthening",
    // Strength — Carries
    "Farmer's Carry",
    "Yoke Carry",
    "Suitcase Carry",
    "Overhead Carry",
    "Front Rack Carry",
    "Rucking",
    // Strength — Core
    "Plank",
    "Side Plank",
    "RKC Plank",
    "Hollow Body Hold",
    "L-Sit",
    "V-Sit",
    "Dead Bug",
    "Bird Dog",
    "Ab Wheel Rollout",
    "Russian Twist",
    "Bicycle Crunch",
    "Leg Raise",
    "Hanging Leg Raise",
    "Cable Crunch",
    "GHD Sit-Up",
    "Back Extension",
    "Reverse Hyperextension",
    "Hyperextension",
    "Pallof Press",
    "Dragon Flag",
    // Strength — Grip / Forearm
    "Farmer's Carry",
    "Wrist Curl",
    "Reverse Wrist Curl",
    "Wrist Roller",
    "Plate Pinch",
    "Towel Pull-Up",
    "Pinch Grip Training",
    "Rice Bucket Training",
    // Olympic Lifting
    "Power Clean",
    "Hang Power Clean",
    "Clean",
    "Hang Clean",
    "Power Snatch",
    "Hang Power Snatch",
    "Snatch",
    "Hang Snatch",
    "Clean and Jerk",
    "Push Jerk",
    "Split Jerk",
    "Clean Pull",
    "Snatch Pull",
    "Clean High Pull",
    "Snatch Balance",
    "Muscle Snatch",
    "Muscle Clean",
    // Kettlebell
    "Kettlebell Swing",
    "Kettlebell Clean",
    "Kettlebell Press",
    "Kettlebell Snatch",
    "Turkish Get-Up",
    "Kettlebell Goblet Squat",
    "Kettlebell Windmill",
    "Kettlebell Row",
    "Bottoms-Up Press",
    // Gymnastics / Calisthenics
    "Handstand",
    "Handstand Walk",
    "Front Lever",
    "Back Lever",
    "Planche",
    "Ring Muscle-Up",
    "Bar Muscle-Up",
    "Skin the Cat",
    "Human Flag",
    "Tuck Planche",
    "Pseudo Planche Push-Up",
    // Cardio / Conditioning
    "Running",
    "Sprinting",
    "Interval Run",
    "Tempo Run",
    "Long Run",
    "Trail Run",
    "Fartlek",
    "Hill Sprints",
    "Jump Rope",
    "Double Unders",
    "Burpee",
    "Mountain Climber",
    "Bear Crawl",
    "Sled Push",
    "Sled Pull",
    "Tire Flip",
    "Battle Ropes",
    "Box Jump",
    "Broad Jump",
    "Assault Bike",
    "SkiErg",
    "Stair Climber",
    "Rowing Ergometer",
    // Track and Field
    "100m Sprint",
    "200m Sprint",
    "400m Run",
    "800m Run",
    "1500m Run",
    "Mile Run",
    "5K Run",
    "10K Run",
    "Half Marathon",
    "Marathon",
    "Long Jump",
    "High Jump",
    "Triple Jump",
    "Shot Put",
    "Discus",
    "Javelin",
    "Pole Vault",
    "Hammer Throw",
    // Cycling
    "Road Cycling",
    "Mountain Biking",
    "Gravel Riding",
    "Stationary Bike",
    "Cycling Hill Climb",
    "Cycling Time Trial",
    "Cycling Criterium",
    "BMX",
    "Downhill Mountain Biking",
    // Swimming
    "Swimming",
    "Freestyle",
    "Backstroke",
    "Breaststroke",
    "Butterfly",
    "Open Water Swim",
    "Aqua Jogging",
    // Rock Climbing — Indoor
    "Bouldering",
    "Sport Climbing",
    "Top Rope",
    "Lead Climbing",
    "Indoor Climbing",
    "Wall Traversal",
    "Moonboard Session",
    "Kilter Board Session",
    "System Board Session",
    "Campus Board Session",
    "Hangboard Session",
    "ARC Training",
    "4x4 Session",
    "Limit Bouldering",
    "Power Endurance Session",
    "Volume Session",
    "Linked Bouldering Circuit",
    // Rock Climbing — Outdoor
    "Outdoor Bouldering",
    "Trad Climbing",
    "Multi-Pitch Climbing",
    "Projecting Session",
    "Onsight Attempt",
    "Flash Attempt",
    "Redpoint Attempt",
    // Rock Climbing — Skills / Drills
    "Footwork Drills",
    "Dynamic Movement Drills",
    "Dyno Practice",
    "Drop Knee Practice",
    "Heel Hook Drills",
    "Toe Hook Drills",
    "Stemming Practice",
    "Mantling Practice",
    "Route Reading",
    "Mental Training",
    "Visualization Practice",
    // Rock Climbing — Finger / Strength
    "Dead Hang",
    "One-Arm Dead Hang",
    "Lock-Off",
    "Max Hang",
    "Repeaters",
    "Weighted Hang",
    "Edge Hang",
    "Sloper Hang",
    "Pinch Block Training",
    "Open Hand Training",
    "Crimp Training",
    "Recruitment Pull",
    // Mountaineering / Alpine
    "Hiking",
    "Day Hike",
    "Backpacking",
    "Summit Attempt",
    "Alpine Climbing",
    "Ice Climbing",
    "Mixed Climbing",
    "Ski Mountaineering",
    "Glacier Travel",
    "Snow Climbing",
    "Scrambling",
    "Ridge Walk",
    "Via Ferrata",
    "Rappelling",
    "Snowshoeing",
    "Crampon Practice",
    "Ice Axe Practice",
    "Self-Arrest Practice",
    // Winter Sports
    "Skiing",
    "Snowboarding",
    "Cross-Country Skiing",
    "Skate Skiing",
    "Nordic Skiing",
    "Speed Skating",
    "Figure Skating",
    // Water Sports
    "Rowing",
    "Kayaking",
    "Canoe",
    "Whitewater Kayaking",
    "Sea Kayaking",
    "Paddleboarding",
    "Surfing",
    "Windsurfing",
    "Kitesurfing",
    "Freediving",
    "Scuba Diving",
    // Combat Sports
    "Boxing",
    "Muay Thai",
    "Brazilian Jiu-Jitsu",
    "Wrestling",
    "Judo",
    "Kickboxing",
    "MMA Training",
    "Heavy Bag Work",
    "Speed Bag Work",
    "Pad Work",
    "Sparring",
    "Grappling",
    // Racket Sports
    "Tennis",
    "Racquetball",
    "Squash",
    "Badminton",
    "Pickleball",
    "Table Tennis",
    // Team Sports
    "Basketball",
    "Soccer",
    "Football",
    "Baseball",
    "Softball",
    "Volleyball",
    "Hockey",
    "Lacrosse",
    "Rugby",
    "Ultimate Frisbee",
    "Water Polo",
    "Handball",
    // Endurance / Multisport
    "Triathlon Training",
    "Duathlon Training",
    "Obstacle Course Race",
    "Rucking",
    // Yoga / Mobility / Recovery
    "Yoga",
    "Hot Yoga",
    "Vinyasa Flow",
    "Yin Yoga",
    "Restorative Yoga",
    "Pilates",
    "Mobility Session",
    "Stretching",
    "Active Recovery",
    "Foam Rolling",
    "Tai Chi",
    "Breathing Practice",
    "Meditation",
    "Cold Exposure",
    "Sauna Session",
    // Parkour / Dance
    "Parkour",
    "Freerunning",
    "Dance",
    "Ballet",
    // Misc
    "Golf",
    "Disc Golf",
    "Archery",
    "Horseback Riding",
    "Sailing",
    "Nordic Walking",
];
